---
abstract: 'Analyze perl files with Perl::Critic'
author:
  - 'Kaare Rasmussen <kaare@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Padre-Plugin-PerlCritic
no_index:
  directory:
    - inc
    - share
    - t
requires:
  Padre: 0.54
  Perl::Critic: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://svn.perlide.org/padre/trunk/Padre-Plugin-PerlCritic/
version: 0.08
